const express=require('express');const Database=require('better-sqlite3');const path=require('path');const fs=require('fs');const crypto=require('crypto');
const app=express();app.use(express.json());const dataDir=process.env.DATA_DIR||'/app/data';fs.mkdirSync(dataDir,{recursive:true});const db=new Database(path.join(dataDir,'betting.db'));db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',active INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id INTEGER NOT NULL,expires_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS houses(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,name TEXT NOT NULL,username TEXT,password TEXT,bonus_day TEXT,bonus_conditions TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS bets(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,datetime TEXT,house_id INTEGER,country TEXT,competition TEXT,home_team TEXT,away_team TEXT,market TEXT,selection TEXT,odds REAL,stake REAL,units REAL,bonus INTEGER DEFAULT 0,result TEXT DEFAULT 'pending',profit REAL DEFAULT 0,notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(house_id) REFERENCES houses(id));
CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,house_id INTEGER,type TEXT,amount REAL,method TEXT,status TEXT,datetime TEXT,notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(house_id) REFERENCES houses(id));
CREATE TABLE IF NOT EXISTS bonuses(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,house_id INTEGER,week_start TEXT,deadline TEXT,required_events INTEGER,min_odds REAL,min_combined_odds REAL,progress INTEGER DEFAULT 0,status TEXT DEFAULT 'open',notes TEXT,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(house_id) REFERENCES houses(id));`);
try{db.exec("ALTER TABLE users ADD COLUMN role TEXT NOT NULL DEFAULT 'user'")}catch(e){} try{db.exec("ALTER TABLE users ADD COLUMN active INTEGER NOT NULL DEFAULT 1")}catch(e){} db.prepare("UPDATE users SET role='admin' WHERE lower(email)=lower(?)").run('vitor.nobrega87@gmail.com');
function hashPassword(password){const salt=crypto.randomBytes(16).toString('hex');const hash=crypto.scryptSync(password,salt,64).toString('hex');return salt+':'+hash}
function verifyPassword(password,stored){const [salt,key]=String(stored).split(':');if(!salt||!key)return false;const hash=crypto.scryptSync(password,salt,64).toString('hex');return crypto.timingSafeEqual(Buffer.from(hash,'hex'),Buffer.from(key,'hex'))}
function token(){return crypto.randomBytes(32).toString('hex')}
function setCookie(res,name,value,maxAge){res.setHeader('Set-Cookie',`${name}=${value}; HttpOnly; Path=/; SameSite=Lax; Max-Age=${maxAge}${process.env.COOKIE_SECURE==='true'?'; Secure':''}`)}
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1).trim())]}))}
function currentUser(req){const t=cookies(req).bt_session;if(!t)return null;const s=db.prepare('SELECT u.id,u.name,u.email,u.role,u.active,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=?').get(t);if(!s||!s.active||new Date(s.expires_at)<=new Date()){if(t)db.prepare('DELETE FROM sessions WHERE token=?').run(t);return null}return s}
app.post('/api/auth/register',(req,res)=>{const name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!name||!email||password.length<8)return res.status(400).json({error:'Nome, email e password com pelo menos 8 caracteres são obrigatórios.'});try{const role=email==='vitor.nobrega87@gmail.com'?'admin':'user';const info=db.prepare('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)').run(name,email,hashPassword(password),role);const t=token();db.prepare("INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,datetime('now','+30 days'))").run(t,info.lastInsertRowid);setCookie(res,'bt_session',t,60*60*24*30);res.json({user:{id:info.lastInsertRowid,name,email,role}})}catch(e){if(String(e.message).includes('UNIQUE'))return res.status(409).json({error:'Já existe uma conta com este email.'});res.status(500).json({error:'Não foi possível criar a conta.'})}});
app.post('/api/auth/login',(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');const u=db.prepare('SELECT id,name,email,password_hash,role,active FROM users WHERE email=?').get(email);if(!u||!u.active||!verifyPassword(password,u.password_hash))return res.status(401).json({error:'Email ou password inválidos.'});const t=token();db.prepare("INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,datetime('now','+30 days'))").run(t,u.id);setCookie(res,'bt_session',t,60*60*24*30);res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.post('/api/auth/logout',(req,res)=>{const t=cookies(req).bt_session;if(t)db.prepare('DELETE FROM sessions WHERE token=?').run(t);setCookie(res,'bt_session','',0);res.json({ok:true})});
app.get('/api/auth/me',(req,res)=>{const u=currentUser(req);if(!u)return res.status(401).json({error:'Não autenticado'});res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.use('/api',(req,res,next)=>{if(req.path.startsWith('/auth/'))return next();const u=currentUser(req);if(!u)return res.status(401).json({error:'Não autenticado'});req.user=u;next()});
const all=(s,...a)=>db.prepare(s).all(...a),run=(s,...a)=>db.prepare(s).run(...a);
const requireAdmin=(req,res,next)=>req.user.role==='admin'?next():res.status(403).json({error:'Acesso reservado ao administrador.'});
app.get('/api/admin/users',requireAdmin,(req,res)=>res.json(all('SELECT id,name,email,role,active,created_at FROM users ORDER BY created_at DESC')));
app.patch('/api/admin/users/:id',requireAdmin,(req,res)=>{const id=Number(req.params.id);if(id===req.user.id&&req.body.active===false)return res.status(400).json({error:'Não podes desativar a tua própria conta.'});const u=db.prepare('SELECT id FROM users WHERE id=?').get(id);if(!u)return res.status(404).json({error:'Utilizador não encontrado.'});if(req.body.active!==undefined)run('UPDATE users SET active=? WHERE id=?',req.body.active?1:0,id);if(req.body.role==='admin'||req.body.role==='user')run('UPDATE users SET role=? WHERE id=?',req.body.role,id);if(req.body.resetSessions)run('DELETE FROM sessions WHERE user_id=?',id);res.json({ok:true})});

app.get('/api/houses',(req,res)=>res.json(all('SELECT id,name,username,bonus_day,bonus_conditions,created_at FROM houses WHERE user_id=? ORDER BY name',req.user.id)));
app.post('/api/houses',(req,res)=>{const x=req.body;run('INSERT INTO houses(user_id,name,username,password,bonus_day,bonus_conditions) VALUES(?,?,?,?,?,?)',req.user.id,x.name,x.username||'',x.password||'',x.bonus_day||'',x.bonus_conditions||'');res.json({ok:true})});
app.get('/api/bets',(req,res)=>res.json(all('SELECT b.*,h.name house_name FROM bets b LEFT JOIN houses h ON h.id=b.house_id AND h.user_id=b.user_id WHERE b.user_id=? ORDER BY datetime(b.datetime) DESC,b.id DESC',req.user.id)));
app.post('/api/bets',(req,res)=>{const x=req.body;run('INSERT INTO bets(user_id,datetime,house_id,country,competition,home_team,away_team,market,selection,odds,stake,units,bonus,result,profit,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',req.user.id,x.datetime,x.house_id||null,x.country||'',x.competition||'',x.home_team||'',x.away_team||'',x.market||'',x.selection||'',Number(x.odds)||0,Number(x.stake)||0,Number(x.units)||0,x.bonus?1:0,x.result||'pending',Number(x.profit)||0,x.notes||'');res.json({ok:true})});
app.put('/api/bets/:id',(req,res)=>{const x=req.body;run('UPDATE bets SET result=?,profit=?,notes=? WHERE id=? AND user_id=?',x.result,x.profit,x.notes||'',req.params.id,req.user.id);res.json({ok:true})});
app.delete('/api/bets/:id',(req,res)=>{run('DELETE FROM bets WHERE id=? AND user_id=?',req.params.id,req.user.id);res.json({ok:true})});
app.get('/api/transactions',(req,res)=>res.json(all('SELECT t.*,h.name house_name FROM transactions t LEFT JOIN houses h ON h.id=t.house_id AND h.user_id=t.user_id WHERE t.user_id=? ORDER BY datetime(t.datetime) DESC,t.id DESC',req.user.id)));
app.post('/api/transactions',(req,res)=>{const x=req.body;run('INSERT INTO transactions(user_id,house_id,type,amount,method,status,datetime,notes) VALUES(?,?,?,?,?,?,?,?)',req.user.id,x.house_id||null,x.type,x.amount,x.method||'',x.status||'completed',x.datetime,x.notes||'');res.json({ok:true})});
app.get('/api/bonuses',(req,res)=>res.json(all('SELECT b.*,h.name house_name FROM bonuses b LEFT JOIN houses h ON h.id=b.house_id AND h.user_id=b.user_id WHERE b.user_id=? ORDER BY deadline',req.user.id)));
app.post('/api/bonuses',(req,res)=>{const x=req.body;run('INSERT INTO bonuses(user_id,house_id,week_start,deadline,required_events,min_odds,min_combined_odds,progress,status,notes) VALUES(?,?,?,?,?,?,?,?,?,?)',req.user.id,x.house_id,x.week_start,x.deadline,x.required_events,x.min_odds,x.min_combined_odds,x.progress||0,x.status||'open',x.notes||'');res.json({ok:true})});
app.put('/api/bonuses/:id',(req,res)=>{const x=req.body;run('UPDATE bonuses SET progress=?,status=?,notes=? WHERE id=? AND user_id=?',x.progress,x.status,x.notes||'',req.params.id,req.user.id);res.json({ok:true})});
app.get('/api/stats',(req,res)=>{const bets=all('SELECT * FROM bets WHERE user_id=?',req.user.id),resolved=bets.filter(x=>x.result!=='pending'),stake=resolved.reduce((s,x)=>s+Number(x.stake||0),0),pnl=resolved.reduce((s,x)=>s+Number(x.profit||0),0),wins=resolved.filter(x=>x.result==='win').length,tx=all(`SELECT COALESCE(SUM(CASE WHEN type IN ('deposit','bonus','adjustment') THEN amount WHEN type='withdrawal' THEN -amount ELSE 0 END),0) balance FROM transactions WHERE user_id=?`,req.user.id)[0].balance;res.json({count:bets.length,resolved:resolved.length,pnl,stake,roi:stake?pnl/stake*100:0,winRate:resolved.length?wins/resolved.length*100:0,balance:Number(tx)+pnl})});
app.get('/api/export',(req,res)=>{const rows=all('SELECT b.datetime,h.name house,b.country,b.competition,b.home_team,b.away_team,b.market,b.selection,b.odds,b.stake,b.units,b.bonus,b.result,b.profit,b.notes FROM bets b LEFT JOIN houses h ON h.id=b.house_id WHERE b.user_id=? ORDER BY b.datetime',req.user.id);const cols=['datetime','house','country','competition','home_team','away_team','market','selection','odds','stake','units','bonus','result','profit','notes'];const esc=v=>'"'+String(v??'').replaceAll('"','""')+'"';res.type('text/csv').send([cols.join(','),...rows.map(x=>cols.map(c=>esc(x[c])).join(','))].join('\n'))});
app.use(express.static(path.join(__dirname,'..','dist')));app.use((req,res)=>res.sendFile(path.join(__dirname,'..','dist','index.html')));app.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('BetTracker running'));